#### Pytorch 설치
###### pip install torch torchvision torchaudio
- torch : pytorch의 핵심 패키지
- torchvision : 컴퓨터 비전을 위한 데이터셋, 모델 아키텍처, 이미지 변환 등
- torchaudio : 오디오 처리와 관련된 도구와 라이브러리 

#### Tensor
- 머신러닝과 딥러닝에서 사용되는 기본적인 데이터 구조
- 다차원배열로 숫자 데이터를 저장하고 조작하는데 사용

#### Tensor의 특징
- 다차원 배열 : Tensor는 1차원(벡터),2치원(행렬), 3차원 이상의 다차원 데이터를 표현
- GPU 지원 : Tensor는 GPU에서 연산을 수행할 수 있어 빠른 계산이 가능
- 자동 미분 : Tensor는 자동미분(AutoGrad) 기능을 지원하며 딥러닝 모델의 학습에 필요한 기울기 계산을 자동으로 수행 

In [2]:
import torch

In [3]:
# 1차원 Tensor 생성
t1 = torch.tensor(
    [1,2,3,4,5]
)
print(t1)

tensor([1, 2, 3, 4, 5])


In [9]:
# 2차원 Tensor 생성
t2 = torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(t2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [6]:
# 3차원 Tensor 생성
t3 = torch.tensor(
    [
        [
            [1],
            [2]
        ],
        [
            [3],
            [4]
        ]
    ]
)
print(t3)

tensor([[[1],
         [2]],

        [[3],
         [4]]])


In [11]:
# Tensor의 크기 확인
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([5])
torch.Size([3, 3])
torch.Size([2, 2, 1])


In [15]:
# Tensor의 데이터 타입 확인 및 변경
print(t1.dtype)
print(type(t1)) # Python의 타입 보기
t1_float = t1.float()
print(t1_float.dtype)
print(t1_float)

torch.int64
<class 'torch.Tensor'>
torch.float32
tensor([1., 2., 3., 4., 5.])


In [17]:
# Tensor의 연산
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a + b)
print(a * b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [21]:
# Tensor의 Indexing과 Slicing
t = torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(t)
print(t[1,1])
print(t[:,1])
print(t[:,-1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(5)
tensor([2, 5, 8])
tensor([3, 6, 9])


In [24]:
# Boolean Masking
t1 = torch.tensor([1,2,3,4,5])
mask = t1 > 3
print(mask)
print(t1[mask])
print(t1[t1>3])

tensor([False, False, False,  True,  True])
tensor([4, 5])
tensor([4, 5])


In [28]:
# Tensor의 reshape : view
t = torch.tensor([1,2,3,4,5,6])
print(t)
t_reshaped1 = t.view(2,3)
t_reshaped2 = t.reshape(2,3)
print(t_reshaped1)
print(t_reshaped2)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [33]:
# Tesor의 차원 변경 : squeeze, unsqueeze
t = torch.tensor([1,2,3])
print(t)
print(t.shape)
print("-" * 20)

# 지정한 위치에 크기가 1인 차원을 추가
t_unsqueeze = t.unsqueeze(0)
print(t_unsqueeze)
print(t_unsqueeze.shape)
print("-" * 20)

# 크기가 1인 차원을 제거(그 차원의 크기가 1일때만 제거 가능)
t_unsqueeze_squeeze = t_unsqueeze.squeeze(0)
print(t_unsqueeze_squeeze)
print(t_unsqueeze_squeeze.shape)


tensor([1, 2, 3])
torch.Size([3])
--------------------
tensor([[1, 2, 3]])
torch.Size([1, 3])
--------------------
tensor([1, 2, 3])
torch.Size([3])


In [39]:
# Ex
x = torch.ones(2,1,2)
print(x.shape)
print(x)
print("-" * 20)

# 모든 크기가 1인 차원 제거 
x_squeezed = x.squeeze()
print(x_squeezed.shape)
print(x_squeezed)
print("-" * 20)

# 특정 차원을 제거
x_squeezed_dim = x.squeeze(dim=1)
print(x_squeezed_dim.shape)
print(x_squeezed_dim)
print("-" * 20)

torch.Size([2, 1, 2])
tensor([[[1., 1.]],

        [[1., 1.]]])
--------------------
torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])
--------------------
torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])
--------------------


In [42]:
# Ex
x = torch.tensor([1,2,3])
print(x.shape)
print(x)
print("-" * 20)

# x의 첫번째 위치에 차원 추가
x_unsqueezed_0 =  x.unsqueeze(0)
print(x_unsqueezed_0.shape)
print(x_unsqueezed_0)
print("-" * 20)

# x의 두번째 위치에 차원 추가
x_unsqueezed_1 = x.unsqueeze(1)
print(x_unsqueezed_1.shape)
print(x_unsqueezed_1)
print("-" * 20)


torch.Size([3])
tensor([1, 2, 3])
--------------------
torch.Size([1, 3])
tensor([[1, 2, 3]])
--------------------
torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])
--------------------


In [48]:
# Tensor의 연결
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t_concat = torch.concat([t1, t2])
t_concat = torch.cat([t1, t2])
print(t_concat)

tensor([1, 2, 3, 4, 5, 6])


In [56]:
# Tensor의 수학 함수
t = torch.tensor([1.0, 2.0, 3.0]) 
print(torch.sin(t))
print(torch.mean(t))
print(torch.min(t))
print(torch.max(t))
print(torch.sum(t))
print(torch.abs(t))

tensor([0.8415, 0.9093, 0.1411])
tensor(2.)
tensor(1.)
tensor(3.)
tensor(6.)
tensor([1., 2., 3.])


In [57]:
# 요소별 연산 : 덧셈
t1 = torch.tensor([1,2,3,4,5])
t_sum = t1 + torch.tensor([5,4,3,2,1])
print(t_sum)

tensor([6, 6, 6, 6, 6])


In [59]:
# 요소별 연산 : 뺄셈
t1 = torch.tensor([1,2,3,4,5])
t_sub= t1 - torch.tensor([5,4,3,2,1])
print(t_sub)

tensor([-4, -2,  0,  2,  4])


In [60]:
# 요소별 연산 : 곱셈
t1 = torch.tensor([1,2,3,4,5])
t_mul= t1 * torch.tensor([5,4,3,2,1])
print(t_mul)

tensor([5, 8, 9, 8, 5])


In [61]:
# 요소별 연산 : 나눗셈
t1 = torch.tensor([1,2,3,4,5])
t_div= t1 / torch.tensor([5,4,3,2,1])
print(t_div)

tensor([0.2000, 0.5000, 1.0000, 2.0000, 5.0000])


In [62]:
# 요소별 제곱
t1 = torch.tensor([1,2,3,4,5])
print(t1**2)

tensor([ 1,  4,  9, 16, 25])


In [66]:
# 행렬 곱셈
t1 = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

t2 = torch.tensor(
    [
        [7],
        [8],
        [9]
    ]
)

matmul_result = torch.matmul(t1, t2)
print(matmul_result)

print(1*7 + 2*8 + 3*9)
print(4*7 + 5*8 + 6*9)

tensor([[ 50],
        [122]])
50
122
